      subroutine tsystem
c
c     Auto-generated by rfq_transop_design.
c     Edit the design YAML, not this generated file.
c
      implicit none
      integer nscav
      real vane, rfp
      nscav = 0
      vane = 5.5200000E-02
      rfp = 0.0000000E+00
      call rfq(75,81,vane,1.5484208E+02,
     $ 1.6200000E+08,rfp,nscav)
      return
      end
